version: '3.8'

services:
  # 1. Database Utama
  postgres-db:
    image: postgres:16-alpine
    container_name: dotnet-postgres
    environment:
      POSTGRES_USER: aldo_user
      POSTGRES_PASSWORD: aldo_password
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Caching Layer (Biar API Cepat)
  redis-cache:
    image: redis:7-alpine
    container_name: dotnet-redis
    ports:
      - "6379:6379"

  # 3. Message Broker (Antrean Notifikasi)
  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: dotnet-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  # 4. Prometheus untuk Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"
    extra_hosts:
        - "host.docker.internal:host-gateway" 

  #5. Grafana untuk Visualisasi
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
volumes:
  postgres_data: